name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Pull DiceDB image
        run: docker pull dicedb/dicedb:latest
      - name: Run DiceDB
        run: docker run -d --name dicedb -p 7379:7379 --restart=always dicedb/dicedb:latest
      - name: Install protoc compiler
        run: sudo apt-get update && sudo apt install -y protobuf-compiler
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm i -g @bufbuild/protoc-gen-es@2.2.5
      - run: npm run compile
      - run: npm run codegen
      - run: npm run build
      - run: npm run test
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
