name: Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Pull DiceDB image
      run: docker pull dicedb/dicedb:latest
    - name: Run DiceDB
      run: docker run -d --name dicedb -p 7379:7379 --restart=always dicedb/dicedb:latest
    - name: Install protoc compiler
      run: sudo apt-get update && sudo apt install -y protobuf-compiler
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i -g @bufbuild/protoc-gen-es@2.2.5
    - run: npm run build
    - name: Run tests
      run: npm run test
